# Generated by Django 4.2.1 on 2023-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_scrape_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='log',
            field=models.TextField(default=None),
        ),
    ]
