# Generated by Django 4.2.1 on 2023-05-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scrape_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
