# Generated by Django 4.2.1 on 2023-06-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_result_page_content_html"),
    ]

    operations = [
        migrations.CreateModel(
            name="Difference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("difference", models.TextField(blank=True, null=True)),
                ("has_difference", models.BooleanField()),
                (
                    "result1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result1",
                        to="api.result",
                    ),
                ),
                (
                    "result2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result2",
                        to="api.result",
                    ),
                ),
            ],
        ),
    ]
