# Generated by Django 4.2.1 on 2023-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_difference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="difference",
            old_name="difference",
            new_name="content_difference",
        ),
        migrations.AddField(
            model_name="difference",
            name="ranking_difference",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="difference",
            name="title_difference",
            field=models.TextField(blank=True, null=True),
        ),
    ]
